SELECT * FROM CPUDATA
SELECT * FROM DISKDATA
SELECT * FROM MEMORYDATA

DBCC CHECKIDENT (CPUDATA, RESEED, 0);

DBCC CHECKIDENT (DISKDATA, RESEED, 0);

DBCC CHECKIDENT (MEMORYDATA, RESEED, 0);

DELETE FROM CPUDATA WHERE ID_CPU != 0
DELETE FROM DISKDATA WHERE ID_DISK != 0
DELETE FROM MEMORYDATA WHERE ID_MEMORIA != 0